### ISSUE TITLE
Option to ignore cached queries

### ISSUE THREAD

**Issue by DannyBen** [makandra/query_diet#12]
I would like to suggest another feature - option to ignore / show cached hits.

In addition to using the widget, I am also using Active Record Query Trace which has a [nice option](https://github.com/ruckus/active-record-query-trace#options) to consider cached queries. This is very helpful, for example, when the widget shows 7 hits, I am worried, but if 3-4 of them are cached, I am much less worried.

Combining this with my previous ticket, I think it would be nice if there is some "config.yml" or proposed initializer code to configure both this option and styling options.

If I was a little more experienced in Rails, I would have attempted to contribute such changes myself, but I am still at my Ape phase...

**Comment by codener** [comment]
This is definitely a nice idea. However, I cannot tell whether we'll have time to look into this soon. Whenever we touch this gem again, we'll surely consider your input. Thanks!

**Comment by codener** [comment]
Closing stale issue.
