### ISSUE TITLE
Allow to pass in a nonce to fulfill the CSP in development

### ISSUE THREAD

**Issue by denzelem** [makandra/query_diet#23]
Since Rails 6 it is possible to use a nonce for style and script tags.

We could allow a user to pass in the nonce as an option:

```
= query_diet_widget(nonce: content_security_policy_nonce) if Rails.env.development?
```

This would require us to change `QueryDiet::Widget` to render the CSS with the nonce. And to extract the onclick handler to a JS script with an nonce, too. Wdyt?

Unfortunately I'm not able to prepare a PR, as my current project has only Rails 5 (which does not allow to use a nonce with inline styles).

**Comment by triskweline** [comment]
Since `query_diet_widget` is already a helper in the same scope, it can retrieve and set `content_security_policy_nonce` itself.
