### ISSUE TITLE
ArgumentError (wrong number of arguments (given 6, expected 1..5))

### ISSUE THREAD

**Issue by trak3r** [makandra/query_diet#31]
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]

rails (7.0.2.2)

query_diet (0.7.0)

```
ArgumentError` (wrong number of arguments (given 6, expected 1..5))
```

no stack trace at all - just that message.

commenting out `gem 'query_diet'` and re-running `bundle install` resolves it.

database driver is `pg (1.3.2)` in case that might be relevant.

**Comment by trak3r** [comment]
perhaps related to changing the signature of the `log()` method?

https://github.com/makandra/query_diet/blob/master/lib/query_diet/active_record_ext.rb#L3

rails 7:

https://github.com/rails/rails/blob/2459c20afb508c987347f52148210d874a9af4fa/activerecord/lib/active_record/connection_adapters/abstract_adapter.rb#L755

**Comment by kratob** [comment]
I had difficulty reproducing this, but I think your hunch with the log method is right. I've released version 0.7.1 which hopefully resolves the issue.

**Comment by trak3r** [comment]
This resolved the issue for me. Thank you! 👏🏻

**Comment by AndraeRay** [comment]
I had the same issue. Upgrading fixed it for me as well.
