### ISSUE TITLE
query diet doesn't reset numbers

### ISSUE THREAD

**Issue by nurettin** [makandra/query_diet#7]
This is my logging configuration: (Rails 3.2.9)
config.log_tags= [:uuid, :remote_ip, lambda { |req| PaperTrail.whodunnit.try(:full_name)|| "Guest" }]

Every time I refresh the page, the same action gets called, but query_diet just adds a fixed number of queries to its counter and doesn't reset itself.

**Comment by codener** [comment]
Is this still an issue? We've never experienced such behaviour and have updated query diet since you filed your issue.
